import * as github from "@actions/github";
import * as core from "@actions/core";
import Axios from "axios";
import * as tmp from "tmp";
import YAML from "yaml";
import { Context } from "@actions/github/lib/context";
import { Octokit } from "@octokit/core";
import { PaginateInterface } from "@octokit/plugin-paginate-rest";
import { Api } from "@octokit/plugin-rest-endpoint-methods/dist-types/types";
import * as fs from "fs";
import * as unzipper from "unzipper";
import _ from "lodash";

import { ArtifactInfo } from "./artifactInfo";
import { JobInfo } from "./jobInfo";

/**
 * Consolidate the output of all jobs that came prior to this job and return as the output of this job.
 */
export class Consolidator {
  octokit: Octokit & Api & { paginate: PaginateInterface };
  context: Context;
  artifacts: ArtifactInfo[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  schema: any;

  /**
   * Initialize clients and member variables.
   */
  constructor() {
    tmp.setGracefulCleanup(); // delete tmp files on process exit

    this.artifacts = [];
    this.octokit = github.getOctokit(`${process.env.GITHUB_TOKEN}`);
    this.context = github.context;
    core.debug("Context:");
    core.debug(JSON.stringify(this.context));
  }

  /**
   * Octokit query parameters that are used across multiple API requests.
   */
  commonQueryParams() {
    return {
      owner: this.context.payload.organization.login,
      repo: `${this.context.payload.repository?.name}`,
      per_page: 100
    };
  }

  /**
   * Runtime entrypoint. Query for the last successful ran (not reran) jobs prior to this job and
   * return the content of the outputs JSON as an output of this job. Outputs of this job will have
   * the same key/name as the strings defined in the `needs` configuration.
   */
  async run() {
    this.schema = await this.getWorkflowSchema();
    this.artifacts = await this.getRunArtifacts();
    for (const [jobName, jobOutputs] of _.toPairs(await this.getJobOutputs())) {
      core.setOutput(jobName, jobOutputs);
    }
  }

  /**
   * Get the GitHub Action Workflow schema for the currently running job. This will query for the
   * YAML file of the current branch and return a data structure.
   */
  async getWorkflowSchema() {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const response: any = await this.octokit.rest.repos.getContent({
      ...this.commonQueryParams(),
      path: this.context.payload.workflow,
      ref: this.context.payload.ref
    });
    core.debug("getContent");
    core.debug(JSON.stringify(response));

    const schema = YAML.parse(
      Buffer.from(response.data.content, "base64").toString("utf8")
    );

    return schema;
  }

  /**
   * Get all jobs running within this workflow.
   */
  getWorkflowJobs(run_id: number): Promise<JobInfo[]> {
    return this.octokit.paginate(
      this.octokit.rest.actions.listJobsForWorkflowRun,
      { ...this.commonQueryParams(), run_id, filter: "all" }
    );
  }

  /**
   * @returns Array of regular expressions that will match the `dependsOn` references for this currently running job that have a `strategy.matrix` defined.
   */
  dependsOnJobNameRegex(): RegExp[] {
    const dependsOnJobDefinitions = _.pick(
      this.schema.jobs,
      this.schema.jobs[this.context.job]?.needs
    );
    return Object.values(dependsOnJobDefinitions).filter((j) => j.strategy?.matrix).map((job) => {
      return new RegExp(`^${job.name} \\(\\S+\\)$`);
    });
  }

  /**
   * @returns (async) Object with attribute keys representing name strings for jobs that the currently running job depends on, and values that correlate to an artifact generated by that job.
   */
  async jobArtifacts(): Promise<{ [k: string]: ArtifactInfo | undefined }> {
    const workflowJobs = await this.getWorkflowJobs(this.context.runId);
    const dependsOnJobs = await this.filterForRelevantJobDetails(workflowJobs);
    return _.mapValues(dependsOnJobs, (job: JobInfo | undefined) =>
      this.artifacts.find((a) => a.name == job?.id.toString())
    );
  }

  /**
   * Get all artifacts associated with this run.
   */
  async getRunArtifacts(): Promise<ArtifactInfo[]> {
    const response = await this.octokit.rest.actions.listWorkflowRunArtifacts({
      ...this.commonQueryParams(),
      run_id: this.context.runId
    });
    core.debug("listWorkflowRunArtifacts");
    core.debug(JSON.stringify(response));

    return response.data.artifacts;
  }

  /**
   * Get the job details for any job that ran with that same definition. Matches the full name immediately followed by open parenthesis.
   * @returns (async) Object with attribute keys representing name strings for jobs that the currently running job depends on, and values that correlate to a JobInfo.
   */
  async filterForRelevantJobDetails(
    workflowJobs: JobInfo[]
  ): Promise<{ [k: string]: JobInfo | undefined }> {
    const jobNameMatchers = this.dependsOnJobNameRegex();
    const jobsThatRan = workflowJobs.filter((job) => job.runner_id);
    const filteredByName = jobsThatRan.filter((job) =>
      jobNameMatchers.find((exp: RegExp) => exp.test(job.name))
    );
    const orderedByRunAttempt = _.orderBy(
      filteredByName,
      "run_attempt",
      "desc"
    );
    const groupedByName = _.groupBy(orderedByRunAttempt, "name");
    const jobsThatGeneratedArtifacts = _.mapValues(groupedByName, (job: Array<JobInfo>) => _.first(job));
    return jobsThatGeneratedArtifacts;
  }

  /**
   * Gather the outputs for the job runs and put them into an object, where each key is the name of a job and the value is the contents of its corresponding artifact.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  async getJobOutputs(): Promise<{ [k: string]: any }> {
    // create a data structure with the job name and associated artifact
    const jobArtifacts = await this.jobArtifacts();

    core.debug(
      `Found Artifacts (${JSON.stringify(
        Object.values(jobArtifacts).map((a) => a?.id)
      )})`
    );

    // need to iterate to avoid defining async callbacks
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const jobResults: { [k: string]: any } = {};
    for (const jobName of Object.keys(jobArtifacts)) {
      const artifact = jobArtifacts[jobName];
      const artifactPath = await this.downloadArtifactFile(artifact?.id);
      jobResults[jobName] = this.readOutputs(artifactPath);
    }
    core.debug(`Job Outputs: ${JSON.stringify(jobResults)}`);

    // return the data structure as an array of objects
    return jobResults;
  }

  /**
   * Download and unpack an artifact to a temporary directory. Return the directory name.
   */
  async downloadArtifactFile(
    artifactId: number | undefined
  ): Promise<string | undefined> {
    if (!artifactId) {
      return undefined;
    }

    const tmpFile = tmp.fileSync();
    const tmpDir = tmp.dirSync();

    // get the artifact download URL
    // artifacts are stored as zip files
    const response = await this.octokit.rest.actions.downloadArtifact({
      ...this.commonQueryParams(),
      artifact_id: artifactId,
      archive_format: "zip"
    });
    core.debug("Artifact URL Info:");
    core.debug(JSON.stringify(response));

    // download the zip file for the artifact
    await this.downloadFile(response.url, tmpFile.name);
    core.debug(`Artifact Zip File Saved To: ${tmpFile.name}`);

    // extract the artifact to a temporary directory
    await fs
      .createReadStream(tmpFile.name)
      .pipe(unzipper.Extract({ path: tmpDir.name }))
      .promise();
    core.debug(
      `Artifact Files Extracted To ${tmpDir.name}: ${JSON.stringify(
        fs.readdirSync(tmpDir.name)
      )}`
    );

    return tmpDir.name;
  }

  /**
   * Read the outputs from the artifact directory path.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  readOutputs(artifactDirectoryPath: string | undefined): any {
    if (!artifactDirectoryPath) {
      return undefined;
    }

    const outputFilename = core.getInput("output_filename");
    const readData = fs.readFileSync(
      `${artifactDirectoryPath}/${outputFilename}`,
      {
        encoding: "utf8",
        flag: "r"
      }
    );
    core.debug(`Output File Contents: ${readData}`);
    return readData;
  }

  /**
   * Download from a HTTPS endpoint and stream directly to file.
   *
   * Sourced from https://stackoverflow.com/questions/55374755/node-js-axios-download-file-stream-and-writefile
   */
  async downloadFile(fileUrl: string, outputLocationPath: string) {
    const writer = fs.createWriteStream(outputLocationPath);

    return Axios({
      method: "get",
      url: fileUrl,
      responseType: "stream"
    }).then((response) => {
      return new Promise((resolve, reject) => {
        response.data.pipe(writer);
        let error: Error | null = null;
        writer.on("error", (err) => {
          error = err;
          writer.close();
          reject(err);
        });
        writer.on("close", () => {
          if (!error) {
            resolve(true);
          }
          //no need to call the reject here, as it will have been called in the
          //'error' stream;
        });
      });
    });
  }
}
